# Generated by Django 3.1.4 on 2021-11-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coviDash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='rumour',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Rumour',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
