# Generated by Django 3.1.4 on 2021-11-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviDash', '0002_auto_20211102_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rumour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
