# Generated by Django 3.1.4 on 2021-11-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviDash', '0003_rumour'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumour',
            name='bodyHtml',
            field=models.TextField(default='HTML Body'),
        ),
        migrations.AddField(
            model_name='rumour',
            name='citation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rumour',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rumour',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='rumour',
            name='img',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.AddField(
            model_name='rumour',
            name='poster',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rumour',
            name='title',
            field=models.CharField(default='Rumour Title', max_length=200),
        ),
        migrations.AddField(
            model_name='rumour',
            name='versource',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rumour',
            name='verusers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
