# Generated by Django 3.1.4 on 2021-11-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coviDash', '0004_auto_20211102_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rumour',
            old_name='bodyHtml',
            new_name='bodyhtml',
        ),
    ]
