# Generated by Django 3.1.4 on 2021-11-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coviDash', '0005_auto_20211102_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rumour',
            old_name='bodyhtml',
            new_name='bodyHtml',
        ),
    ]
