# Generated by Django 3.1.4 on 2021-11-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviDash', '0006_auto_20211102_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumour',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
