# Generated by Django 3.1.4 on 2021-11-03 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviDash', '0007_auto_20211102_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rumour',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
