# Generated by Django 3.1.4 on 2021-11-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviDash', '0009_auto_20211102_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumour',
            name='validity',
            field=models.CharField(default='Mixed', max_length=200),
        ),
    ]
