# Generated by Django 3.1.4 on 2021-11-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviDash', '0010_rumour_validity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rumour',
            name='versource',
        ),
        migrations.RemoveField(
            model_name='rumour',
            name='verusers',
        ),
        migrations.AddField(
            model_name='rumour',
            name='versourceF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rumour',
            name='versourceT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rumour',
            name='verusersF',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rumour',
            name='verusersT',
            field=models.IntegerField(default=0),
        ),
    ]
