# Generated by Django 3.1.4 on 2021-11-14 15:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coviDash', '0013_auto_20211113_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity', models.CharField(default='False', max_length=200)),
                ('rumour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coviDash.rumour')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('validity', models.CharField(default='False', max_length=200)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rumour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coviDash.rumour')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='Comment Body')),
                ('validity', models.CharField(default='False', max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rumour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coviDash.rumour')),
            ],
        ),
    ]
