# Generated by Django 3.2.9 on 2021-11-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviDash', '0014_comment_source_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='title',
            field=models.CharField(default='Source Title', max_length=200),
        ),
    ]
