# Generated by Django 3.1.4 on 2021-11-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviDash', '0019_remove_comment_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
