# Generated by Django 3.2.9 on 2021-11-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coviDash', '0021_rumour_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rumour',
            name='verusers',
        ),
        migrations.RemoveField(
            model_name='rumour',
            name='verusersF',
        ),
        migrations.RemoveField(
            model_name='rumour',
            name='verusersT',
        ),
    ]
