# Generated by Django 3.1.4 on 2021-11-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='role',
            field=models.CharField(default='regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='title',
            field=models.CharField(default='Amateur Sleuth', max_length=50),
        ),
    ]
