# Generated by Django 3.2.9 on 2021-11-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211114_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='added',
        ),
        migrations.RemoveField(
            model_name='details',
            name='cited',
        ),
        migrations.RemoveField(
            model_name='details',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='details',
            name='solved',
        ),
        migrations.RemoveField(
            model_name='details',
            name='title',
        ),
        migrations.RemoveField(
            model_name='details',
            name='updoots',
        ),
        migrations.RemoveField(
            model_name='details',
            name='voted',
        ),
        migrations.AddField(
            model_name='details',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
