# Generated by Django 3.2.9 on 2021-11-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviDash', '0021_rumour_edited'),
        ('users', '0006_auto_20211115_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='involved',
            field=models.ManyToManyField(to='coviDash.Rumour'),
        ),
    ]
