# Generated by Django 3.2.9 on 2021-11-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_details_involved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='involved',
            new_name='subscribed',
        ),
    ]
